Added test for IS-199

diff --git a/bdii/trunk/tests/test-bdii b/bdii/trunk/tests/test-bdii
--- a/bdii/trunk/tests/test-bdii
+++ b/bdii/trunk/tests/test-bdii
@@ -116,6 +116,16 @@ else
     echo "OK"
 fi 
 
+echo -n "Testing two plugins extending the attribute: "
+filter="GlueServiceUniqueID=service_7"
+${command} ${filter} | grep "vo_1" >/dev/null 2>/dev/null 
+if [ $? -gt 0 ]; then
+    echo "FAIL"
+    RETVAL=1
+else
+    echo "OK"
+fi 
+
 rm -f ${working_dir}/ldif/service-long-dn.ldif
 rm -f ${working_dir}/ldif/service-unstable.ldif
 rm -f ${working_dir}/ldif/service-spaces-2.ldif
